- name: Configure Alpine Homelab
  hosts: alpine
  become: true
  tasks:
    - name: Ensure all repos are added
      ansible.builtin.lineinfile:
        path: /etc/apk/repositories
        line: "{{item}}"
        state: present
      loop:
        - "http://dl-cdn.alpinelinux.org/alpine/v3.22/main"
        - "http://dl-cdn.alpinelinux.org/alpine/edge/testing"
        - "http://dl-cdn.alpinelinux.org/alpine/edge/community"
        - "http://dl-cdn.alpinelinux.org/alpine/v3.22/community"
    - name: pacages are installed
      apk:
        name: "{{item}}"
        state: present
      loop:
        - tmux
        - git
        - neovim
        - python3
        - py3-pip
        - neofetch
