- name: Configure Alpine Homelab
  hosts: alpine
  become: true
  tasks:
    - name: Ensure neovim is installed
      apk:
        name: neovim
        state: present
    - name: Ensure python is installed
      apk:
        name: python3
        state: present
    - name: Ensure pip is installed
      apk:
        name: py3-pip
        state: present
    - name: Ensure edge/testing repository is added
      ansible.builtin.lineinfile:
        path: /etc/apk/repositories
        line: "http://dl-cdn.alpinelinux.org/alpine/edge/testing"
        state: present
    - name: Ensure neofetch is installed
      apk:
        name: neofetch
        state: present
    - name: Ensure git is installed
      apk:
        name: git
        state: present
    - name: Ensure tmux is installed
      apk:
        name: tmux
        state: present
